# Generated by Django 5.0 on 2024-08-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_app", "0002_examtimetableplan_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="examtimetableplan",
            name="course_set",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="examtimetableplan",
            name="venue_set",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
