# Generated by Django 5.0 on 2024-08-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "plan_app",
            "0004_rename_course_set_examtimetableplan_course_set_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="examtimetableplan",
            name="constraints",
            field=models.TextField(default="No constraints was added"),
        ),
    ]
