# Generated by Django 5.0 on 2024-10-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_app", "0006_course_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("HNDI", "HNDI"),
                    ("HNDII", "HNDII"),
                    ("NDI", "NDI"),
                    ("NDII", "NDII"),
                ],
                default="",
                max_length=5,
            ),
            preserve_default=False,
        ),
    ]
