# Generated by Django 5.0 on 2024-10-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_app", "0007_alter_course_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=10),
        ),
    ]
