# Generated by Django 5.0 on 2024-11-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_app", "0008_alter_course_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examtimetableplan",
            name="constraints",
            field=models.TextField(blank=True, null=True),
        ),
    ]
